spring.application.name=Fligth_Booking_System
spring.datasource.url= jdbc:postgresql://localhost:5432/Fligth_Booking_System_Db
spring.datasource.username=postgres
spring.datasource.password=6113
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
